# Generated by Django 3.2.5 on 2021-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210801_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(default='ubuntu', max_length=50),
            preserve_default=False,
        ),
    ]
