# Generated by Django 3.2.5 on 2021-08-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
